### ISSUE TITLE
使用WebApiClient提供的缓存提供者接口

### ISSUE THREAD

**Issue by xljiulang** [yrinleung/EasyCaching.Extensions#2]
hi，0.3.5的webApiClient新增了[IResponseCacheProvider](https://github.com/dotnetcore/WebApiClient/blob/master/WebApiClient/IResponseCacheProvider.cs)接口，可以考虑使用此接口。

**Comment by yrinleung** [comment]
非常感谢您提的建议，我先研究下webApiClient新接口的能力。

**Comment by yrinleung** [comment]
非常抱歉，由于IResponseCacheProvider接口中Get和Set所提供的参数不足以识别出EasyCaching的EasyCachingAbleAttribute、EasyCachingPutAttribute、EasyCachingEvictAttribute。
为了不改变用户使用EasyCaching的Interceptor习惯，所以还是使用WebApiClient的ApiInterceptor去实现。

**Comment by xljiulang** [comment]
那我建议你继承ApiInterceptor，重写GetApiActionDescriptor方法，在你的ApiActionDescriptor子类里相办法将ApiAction声明的EasyCachingAbleAttribute包装为IApiActionCacheAttribute设置到ApiActionDescriptor子类的Cache属性。

**Comment by xljiulang** [comment]
代码思路如下：
```
class MyApiActionDescriptor : ApiActionDescriptor
{
    public MyApiActionDescriptor(MethodInfo method)
        : base(method)
    {
        var easyCachingAble = method.GetCustomAttribute<EasyCachingAbleAttribute>();
        if (easyCachingAble != null)
        {
            this.Cache = new ActionCacheAttribute(easyCachingAble);
        }
    }

    private class ActionCacheAttribute : Attribute, IApiActionCacheAttribute
    {
        ...
    }
}
```

**Comment by yrinleung** [comment]
OK。

**Comment by yrinleung** [comment]
@xljiulang 在1.0.2版本中使用IResponseCacheProvider接口了

**Comment by xljiulang** [comment]
觉得在高频方法里调用了太多了反射，这些反射结果可以在对象创建时反射获取并缓存起来。已经提交一个pr
